# Generated by Django 5.2.17 on 2026-08-09 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True, verbose_name='ID en mhw-db')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(choices=[('head', 'Cabeza'), ('chest', 'Pecho'), ('gloves', 'Brazos'), ('waist', 'Cintura'), ('legs', 'Piernas')], db_index=True, max_length=20)),
                ('rank', models.CharField(choices=[('low', 'Low Rank'), ('high', 'High Rank'), ('master', 'Master Rank')], db_index=True, default='low', max_length=20)),
                ('rarity', models.PositiveSmallIntegerField(default=1)),
                ('defense_base', models.PositiveIntegerField(default=0)),
                ('defense_max', models.PositiveIntegerField(default=0)),
                ('defense_augmented', models.PositiveIntegerField(default=0)),
                ('resist_fire', models.SmallIntegerField(default=0)),
                ('resist_water', models.SmallIntegerField(default=0)),
                ('resist_thunder', models.SmallIntegerField(default=0)),
                ('resist_ice', models.SmallIntegerField(default=0)),
                ('resist_dragon', models.SmallIntegerField(default=0)),
                ('slots', models.JSONField(blank=True, default=list)),
                ('assets', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True, verbose_name='ID en mhw-db')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('rarity', models.PositiveSmallIntegerField(default=1)),
                ('carry_limit', models.PositiveSmallIntegerField(default=0)),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Precio de venta')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True, verbose_name='ID en mhw-db')),
                ('name', models.CharField(max_length=100)),
                ('zone_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True, verbose_name='ID en mhw-db')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('max_level', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True, verbose_name='ID en mhw-db')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(choices=[('large', 'Grande'), ('small', 'Pequeño')], default='large', max_length=20)),
                ('species', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('locations', models.ManyToManyField(blank=True, related_name='monsters', to='core.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonsterAilment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ailments', to='core.monster')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonsterResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(db_index=True, max_length=20)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistances', to='core.monster')),
            ],
            options={
                'ordering': ['element'],
            },
        ),
        migrations.CreateModel(
            name='MonsterReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_rewards', to='core.item')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='core.monster')),
            ],
            options={
                'ordering': ['monster', 'item'],
            },
        ),
        migrations.CreateModel(
            name='ArmorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_skills', to='core.armor')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_skills', to='core.skill')),
            ],
            options={
                'ordering': ['armor', 'skill'],
            },
        ),
        migrations.AddField(
            model_name='armor',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='armors', through='core.ArmorSkill', to='core.skill'),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True, verbose_name='ID en mhw-db')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('weapon_type', models.CharField(choices=[('great-sword', 'Great Sword'), ('long-sword', 'Long Sword'), ('sword-and-shield', 'Sword & Shield'), ('dual-blades', 'Dual Blades'), ('hammer', 'Hammer'), ('hunting-horn', 'Hunting Horn'), ('lance', 'Lance'), ('gunlance', 'Gunlance'), ('switch-axe', 'Switch Axe'), ('charge-blade', 'Charge Blade'), ('insect-glaive', 'Insect Glaive'), ('light-bowgun', 'Light Bowgun'), ('heavy-bowgun', 'Heavy Bowgun'), ('bow', 'Bow')], db_index=True, max_length=30)),
                ('damage_type', models.CharField(choices=[('sever', 'Corte'), ('blunt', 'Impacto'), ('ammo', 'Disparo')], default='sever', max_length=20)),
                ('rarity', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('attack_display', models.PositiveIntegerField(default=0, verbose_name='Daño mostrado')),
                ('attack_raw', models.PositiveIntegerField(default=0, verbose_name='Raw real')),
                ('affinity', models.SmallIntegerField(default=0, verbose_name='Afinidad %')),
                ('defense', models.PositiveIntegerField(default=0, verbose_name='Bono de defensa')),
                ('elderseal', models.CharField(blank=True, default='', max_length=20)),
                ('elements', models.JSONField(blank=True, default=list)),
                ('sharpness', models.JSONField(blank=True, default=dict)),
                ('slots', models.JSONField(blank=True, default=list)),
                ('craftable', models.BooleanField(default=False)),
                ('crafting_cost', models.PositiveIntegerField(default=0, verbose_name='Coste zenny')),
                ('assets', models.JSONField(blank=True, default=dict)),
                ('branches', models.ManyToManyField(blank=True, related_name='upgrades_from', to='core.weapon')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.weapon', verbose_name='Arma anterior (upgrade)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CraftingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('forge', 'Forja'), ('upgrade', 'Mejora')], default='forge', max_length=20, verbose_name='Tipo de material')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='core.item')),
            ],
            options={
                'ordering': ['item'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_crafti_content_7babfd_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'item', 'kind'), name='uniq_crafting_material')],
            },
        ),
        migrations.CreateModel(
            name='Hitzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(db_index=True, max_length=100)),
                ('cut', models.PositiveSmallIntegerField(default=0, verbose_name='Corte')),
                ('impact', models.PositiveSmallIntegerField(default=0, verbose_name='Impacto')),
                ('shot', models.PositiveSmallIntegerField(default=0, verbose_name='Disparo')),
                ('fire', models.PositiveSmallIntegerField(default=0)),
                ('water', models.PositiveSmallIntegerField(default=0)),
                ('thunder', models.PositiveSmallIntegerField(default=0)),
                ('ice', models.PositiveSmallIntegerField(default=0)),
                ('dragon', models.PositiveSmallIntegerField(default=0)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitzones', to='core.monster')),
            ],
            options={
                'ordering': ['part'],
                'constraints': [models.UniqueConstraint(fields=('monster', 'part'), name='uniq_monster_hitzone_part')],
            },
        ),
        migrations.CreateModel(
            name='MonsterWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(db_index=True, max_length=20)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('condition', models.CharField(blank=True, default='', max_length=100)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='core.monster')),
            ],
            options={
                'ordering': ['-stars'],
                'constraints': [models.UniqueConstraint(fields=('monster', 'element', 'condition'), name='uniq_monster_element_weakness')],
            },
        ),
        migrations.CreateModel(
            name='SkillRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('modifiers', models.JSONField(blank=True, default=dict)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='core.skill')),
            ],
            options={
                'ordering': ['skill', 'level'],
                'constraints': [models.UniqueConstraint(fields=('skill', 'level'), name='uniq_skill_level')],
            },
        ),
    ]
