# Generated by Django 5.2.17 on 2026-08-09 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True, verbose_name='ID en mhw-db')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('rarity', models.PositiveSmallIntegerField(default=1)),
                ('slot', models.PositiveSmallIntegerField(default=1, verbose_name='Ranura')),
            ],
            options={
                'ordering': ['slot', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True, verbose_name='ID en mhw-db')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('rarity', models.PositiveSmallIntegerField(default=1)),
                ('crafting_cost', models.PositiveIntegerField(default=0, verbose_name='Coste zenny')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.charm', verbose_name='Amuleto anterior')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharmSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('charm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charm_skills', to='core.charm')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charm_skills', to='core.skill')),
            ],
            options={
                'ordering': ['charm', 'skill'],
            },
        ),
        migrations.AddField(
            model_name='charm',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='charms', through='core.CharmSkill', to='core.skill'),
        ),
        migrations.CreateModel(
            name='DecorationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoration_skills', to='core.decoration')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoration_skills', to='core.skill')),
            ],
            options={
                'ordering': ['decoration', 'skill'],
            },
        ),
        migrations.AddField(
            model_name='decoration',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='decorations', through='core.DecorationSkill', to='core.skill'),
        ),
    ]
