# Generated by Django 5.2.17 on 2026-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_decoration_charm_charmskill_charm_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nivel/rango'),
        ),
        migrations.AlterField(
            model_name='charm',
            name='game_id',
            field=models.IntegerField(db_index=True, verbose_name='ID en mhw-db'),
        ),
        migrations.AddConstraint(
            model_name='charm',
            constraint=models.UniqueConstraint(fields=('game_id', 'name'), name='uniq_charm_game_name'),
        ),
    ]
