# Generated by Django 5.2.17 on 2026-08-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_charm_level_alter_charm_game_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50, unique=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='armor',
            name='type',
            field=models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('gloves', 'Arms'), ('waist', 'Waist'), ('legs', 'Legs')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='monster',
            name='type',
            field=models.CharField(choices=[('large', 'Large'), ('small', 'Small')], default='large', max_length=20),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage_type',
            field=models.CharField(choices=[('sever', 'Sever'), ('blunt', 'Blunt'), ('ammo', 'Ammo')], default='sever', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='armorskill',
            constraint=models.UniqueConstraint(fields=('armor', 'skill'), name='uniq_armor_skill'),
        ),
        migrations.AddConstraint(
            model_name='charmskill',
            constraint=models.UniqueConstraint(fields=('charm', 'skill'), name='uniq_charm_skill'),
        ),
        migrations.AddConstraint(
            model_name='decorationskill',
            constraint=models.UniqueConstraint(fields=('decoration', 'skill'), name='uniq_decoration_skill'),
        ),
        migrations.AddConstraint(
            model_name='monsterailment',
            constraint=models.UniqueConstraint(fields=('monster', 'name'), name='uniq_monster_ailment_name'),
        ),
        migrations.AddConstraint(
            model_name='monsterresistance',
            constraint=models.UniqueConstraint(fields=('monster', 'element'), name='uniq_monster_resistance_element'),
        ),
        migrations.AddConstraint(
            model_name='monsterreward',
            constraint=models.UniqueConstraint(fields=('monster', 'item'), name='uniq_monster_reward_item'),
        ),
    ]
